name: Intégration et Déploiement Continus (CI/CD) - HYDRA

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-publish:
    name: Construire et Publier l'image Docker
    runs-on: ubuntu-latest

    # 1. On donne au serveur les droits d'écriture sur le registre de ton dépôt
    permissions:
      contents: read
      packages: write

    steps:
      - name: Récupération du code source
        uses: actions/checkout@v4

      # 2. Le serveur s'authentifie sur le GitHub Container Registry (GHCR)
      - name: Connexion au registre GitHub (GHCR)
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # 3. Construction et envoi de l'image
      - name: Build et Push
        run: |
          # Astuce réseau : Docker exige des adresses en minuscules. 
          # On convertit automatiquement le nom de ton dépôt (Team-Hydra-224...) en minuscules.
          IMAGE_ID=$(echo "ghcr.io/${{ github.repository }}" | tr '[:upper:]' '[:lower:]')

          echo "Construction de l'image : $IMAGE_ID:latest"
          docker build -t $IMAGE_ID:latest .

          echo "Envoi de l'image sur le registre..."
          docker push $IMAGE_ID:latest
